#!/bin/sh

LUAROCKS_SYSCONFDIR='/opt/homebrew/etc/luarocks' exec '/opt/homebrew/opt/lua/bin/lua5.4' -e 'package.path="/Users/al/.luarocks/share/lua/5.4/?.lua;/Users/al/.luarocks/share/lua/5.4/?/init.lua;/opt/homebrew/share/lua/5.4/?.lua;/opt/homebrew/share/lua/5.4/?/init.lua;"..package.path;package.cpath="/Users/al/.luarocks/lib/lua/5.4/?.so;/opt/homebrew/lib/lua/5.4/?.so;"..package.cpath;local k,l,_=pcall(require,"luarocks.loader") _=k and l.add_context("busted","2.2.0-1")' '/opt/homebrew/lib/luarocks/rocks-5.4/busted/2.2.0-1/bin/busted' "$@"
